### ISSUE TITLE
Errors during install

### ISSUE THREAD

**Issue by wouterbeek** [IBCNServices/pyRDF2Vec#5]
When I try to install using the `python -m` prefix (full command: `python3 -m pip install pyRDF2Vec &> log.out`) installation emits the following errors:

```
        analyzeline(m, pat[1], line)
      File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 1098, in analyzeline
        last_name = updatevars(typespec, selector, attr, edecl)
      File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 1542, in updatevars
        attrspec = [x.strip() for x in markoutercomma(attrspec).split('@,@')]
      File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
        assert not f, repr((f, line, l))
    AssertionError: (-1, 'intent(in))', 'intent(in))')
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wz2xi_lr/scipy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wz2xi_lr/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-krxuqpuw/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/wouter/.local/include/python3.7m/scipy Check the logs for full command output.
```

I have included the full logs for completeness: [out.log](https://github.com/IBCNServices/pyRDF2Vec/files/4374661/out.log)

**Comment by GillesVandewiele** [comment]
Hi Wouter, 

Thanks for reporting this. We are looking into it. Do you have the python dev tools installed? (`sudo apt-get install python3-dev`)

**Comment by GillesVandewiele** [comment]
If that doesn't work, could you just try to run `example.py` and install the necessary dependencies manually through pip? Our requirements.txt is probably not in the correct order, or has some version mismatch between packages...

**Comment by wouterbeek** [comment]
@GillesVandewiele Yes I have the Python dev tools installed (version 3.7.5).  Let me test the `example.py` thing...

**Comment by wouterbeek** [comment]
@GillesVandewiele I was able to install a couple of packages that way, but after installing package `community` I get the following:

```
$ python3 example.py 
Traceback (most recent call last):
  File "example.py", line 20, in <module>
    from rdf2vec import RDF2VecTransformer
  File "/home/wouter/tmp/pyRDF2Vec/rdf2vec/rdf2vec.py", line 10, in <module>
    from walkers.random import RandomWalker
  File "/home/wouter/tmp/pyRDF2Vec/rdf2vec/walkers/__init__.py", line 2, in <module>
    from .community import *
  File "/home/wouter/tmp/pyRDF2Vec/rdf2vec/walkers/community.py", line 13, in <module>
    community.community_louvain.check_random_state = check_random_state
AttributeError: module 'community' has no attribute 'community_louvain'
```

I don't know how to install / fix the attribute.

**Comment by GillesVandewiele** [comment]
Hmm let me look into how to fix that one. In the meantime, you can probably use all other Walking strategies (so not importing `CommunityWalker` in the example.py and removing its references).

**Comment by GillesVandewiele** [comment]
Concerning the community error, did you do `pip install community`? If so, you will have to remove that one `pip uninstall community` and install `pip install python-louvain`

**Comment by wouterbeek** [comment]
Thanks, that's where I went wrong (`community ` and `louvain` are the not same package as `python-louvain`).

Now I get this:
```
$ python3 example.py 
100%|████████████████████████████████████████████████████████████████████████████████████████| 74567/74567 [00:01<00:00, 47390.73it/s]
Traceback (most recent call last):
  File "example.py", line 53, in <module>
    ngram_walker = NGramWalker(2, float('inf'), n_wildcards=1)
TypeError: __init__() got an unexpected keyword argument 'n_wildcards'
```

**Comment by GillesVandewiele** [comment]
Hi Wouter,

It seems like we forgot to update our `example.py` in the latest release...The interface of the NGramWalker did indeed change. The argument is now called `wildcards` and accepts a list of wildcard values. `wildcards=[1]` will work.

I will push a fix to PyPi for this in the nearby future. We are sorry for the inconvenience.

Thanks for reporting all this, greatly appreciated!

**Comment by GillesVandewiele** [comment]
Here's a more minimal example.py:
```python3
import random
import os
import numpy as np

os.environ['PYTHONHASHSEED'] = '42'
random.seed(42)
np.random.seed(42)

import rdflib
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.manifold import TSNE

from converters import rdflib_to_kg
from rdf2vec import RDF2VecTransformer

from walkers import RandomWalker

import warnings
warnings.filterwarnings('ignore')

# Load our train & test instances and labels
test_data = pd.read_csv('../data/MUTAG_test.tsv', sep='\t')
train_data = pd.read_csv('../data/MUTAG_train.tsv', sep='\t')

train_people = [rdflib.URIRef(x) for x in train_data['bond']]
train_labels = train_data['label_mutagenic']

test_people = [rdflib.URIRef(x) for x in test_data['bond']]
test_labels = test_data['label_mutagenic']

all_labels = list(train_labels) + list(test_labels)

# Define the label predicates, all triples with these predicates
# will be excluded from the graph
label_predicates = [
    'http://dl-learner.org/carcinogenesis#isMutagenic'
]

# Convert the rdflib to our KnowledgeGraph object
kg = rdflib_to_kg('../data/mutag.owl', label_predicates=label_predicates)

random_walker = RandomWalker(2, float('inf'))

# Create embeddings with random walks
transformer = RDF2VecTransformer(walkers=[random_walker], sg=1)
walk_embeddings = transformer.fit_transform(kg, train_people + test_people)

# Fit model on the walk embeddings
train_embeddings = walk_embeddings[:len(train_people)]
test_embeddings = walk_embeddings[len(train_people):]

rf =  RandomForestClassifier(random_state=42, n_estimators=100)
rf.fit(train_embeddings, train_labels)

print('Random Forest:')
print(accuracy_score(test_labels, rf.predict(test_embeddings)))
print(confusion_matrix(test_labels, rf.predict(test_embeddings)))

clf =  GridSearchCV(SVC(random_state=42), {'kernel': ['linear', 'poly', 'rbf'], 'C': [10**i for i in range(-3, 4)]})
clf.fit(train_embeddings, train_labels)

print('Support Vector Machine:')
print(accuracy_score(test_labels, clf.predict(test_embeddings)))
print(confusion_matrix(test_labels, clf.predict(test_embeddings)))
```

**Comment by wouterbeek** [comment]
@GillesVandewiele Thanks for helping me out.  The minimal example is working for me.  I will close this issue after the new `example.py` is pushed and I have tested that.

Thanks again!

**Comment by GillesVandewiele** [comment]
Hi Wouter. The issues should be fixed. Could you confirm?

**Comment by wouterbeek** [comment]
Installation works, so I'm closing this one.  But I'm opening a new issue for an error that comes up when I run `python example.py`: #7
