### ISSUE TITLE
Value error when running the example

### ISSUE THREAD

**Issue by wouterbeek** [IBCNServices/pyRDF2Vec#7]
When I run the example script (`python example.py`) I get the following error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 4238, in scatter
    raise ValueError
```

I also include the full output for completeness' sake:

```
$ python3 example.py 
100%|████████████████████████████████████████████████████████████████████████| 74567/74567 [00:01<00:00, 49093.55it/s]
Extracted 52871 walks for 340 instances!
Support Vector Machine: Accuracy = 0.7647058823529411
[[44  1]
 [15  8]]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 4238, in scatter
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 95, in <module>
    facecolors=[color_map[i] for i in all_labels],
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 2864, in scatter
    is not None else {}), **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 4245, in scatter
    .format(nc=n_elem, xs=x.size, ys=y.size)
ValueError: 'c' argument has 340 elements, which is not acceptable for use with 'x' with size 272, 'y' with size 272.
```

**Comment by GillesVandewiele** [comment]
Ok makes sense! Weird that this didn't crash on my computer. Should be fixed now.

Thanks again btw!

**Comment by GillesVandewiele** [comment]
(at least fixed after me messing up a few times...)

**Comment by wouterbeek** [comment]
Thanks for fixing this!
